FROM elixir:1.18.1-otp-27-slim

RUN apt-get update -y && \
    apt-get install -y inotify-tools git && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install hex + rebar
RUN mix local.hex --force && mix local.rebar --force

# Cache dependencies
COPY mix.exs mix.lock ./
RUN mix deps.get

COPY . .

EXPOSE 4000

CMD ["sh", "-c", "mix deps.get && mix ecto.setup && mix phx.server"]
